### PR TITLE
Extend possibiliies with many news functions

### PR DESCRIPTION
**Pull request by oopen**
Big addition of functions.

Get sensor by index, string, DeviceAddress.
Convert address in each format.
Validate a address range.
and many more.

Only lite breaking changes in begin() & callback's() parameters.

### CODE REVIEW

**Comment by Gbertaz** [comment]
Thank you @oopen. I noticed a couple of typos and outdated info in the wiki. I will fix them and merge everything soon.

**Comment by oopen** [comment]
Hello @Gbertaz can I make something to merge the request?

**Comment by Gbertaz** [comment]
Hello @oopen, sorry I was a bit busy lately. I invited you as collaborator. You should be able to merge

**Review by Gbertaz — APPROVED** [review]

**Comment by oopen** [comment]
I was no able to merge myself.

Can you also push to platformio ? current version on it, still 1.0.4 not 1.1.0

Thanks you for merging.

**Pull request merged**
