### PR TITLE
Update NonBlockingDallas.cpp

### PR DESCRIPTION
**Pull request by dzsoni**
Error values from DallasTemperature.h.

### CODE REVIEW

**Comment by dzsoni** [comment]
Please review my suggestion. 
The DallasTemperature::getTempC and DallasTemperature::getTempF returns with  DEVICE_DISCONNECTED_C  (-127) and 
DEVICE_DISCONNECTED_F  (-196.6) if we can't read the temp. Where does your 85.0 value come from?
(DEVICE_DISCONNECTED_C i and F are defined in  DallasTemperature.h.)

**Review by Gbertaz — APPROVED** [review]

**Comment by Gbertaz** [comment]
Hi, thank you for the correction. The value 85.0 is wrong, my bad. However according to DallasTemperature Readme:

> _In case of temperature conversion problems (result is -85)_

Should we check against -85 as well?

**Comment by dzsoni** [comment]
Tell the true, I don't know, but you can find  many pages about this topc. 85.0 is the power-on reset value of the temperature register , and after power up, you must issue "requestTemperatures" in order to read valid temp. Many pople miss it or not let enought time to the conversion? thanks for the lib anyway :)
https://forum.arduino.cc/t/why-does-this-fix-work-for-ds18b20-error-code-85/529580/2

**Comment by Gbertaz** [comment]
You are welcome, I hope you find the lib useful and thank you for participating. I will dig into this topic

**Comment by ericnev** [comment]
> You are welcome, I hope you find the lib useful and thank you for participating. I will dig into this topic

I'm hitting this myself, and I'm curious what I'm doing wrong - the DallasTemperature library (blocking) is working as intended, but my callbacks return nothing but 85C after following the tutorial here.

**Pull request merged**
